# Конфигурация cargo-deny для проверки безопасности зависимостей

[advisories]
# Проверка на уязвимости
vulnerability = "deny"
unmaintained = "warn"
unsound = "deny"
notice = "warn"

# Исключения для известных проблем
exceptions = [
    # Добавить сюда исключения при необходимости
]

[licenses]
# Разрешенные лицензии
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unlicense",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0",
    "MIT-0",
]

# Запрещенные лицензии
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
]

# Исключения для лицензий
exceptions = [
    # Добавить сюда исключения при необходимости
]

# Копилефт лицензии
copyleft = "warn"

# Неизвестные лицензии
unknown = "warn"

[source]
# Настройки источников зависимостей
registry = "https://github.com/rust-lang/crates.io-index"
git = "https://github.com/rust-lang/cargo"

[source."https://github.com/rust-lang/crates.io-index"]
# Настройки для crates.io
replace-with = "vendored-sources"

[source.vendored-sources]
# Использование локальных источников
directory = "vendor"

[bans]
# Настройки запретов
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

# Исключения для множественных версий
exceptions = [
    # Добавить сюда исключения при необходимости
]

[workspace]
# Настройки рабочего пространства
exclude = [
    "target",
    "examples",
    "tests",
]

[target.'cfg(target_os = "windows")']
# Специфичные настройки для Windows
advisories = { vulnerability = "deny", unmaintained = "warn" }

[target.'cfg(target_os = "linux")']
# Специфичные настройки для Linux
advisories = { vulnerability = "deny", unmaintained = "warn" }

[target.'cfg(target_os = "macos")']
# Специфичные настройки для macOS
advisories = { vulnerability = "deny", unmaintained = "warn" }